version: "3.9"

services:
  backend:
    build: .
    container_name: node-backend
    working_dir: /app
    command: sh -c "npm run wait-for-db && npm run dev"
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASS: anil123
      DB_NAME: testdb
      DB_DIALECT: mysql
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
    restart: always

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anil123
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: anil123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
