version: "3.8"

services:
  db:
    image: mysql:8.4
    container_name: master-o-back-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: myapp_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: master-o-back
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: sh -c "sleep 15 && node dist/app.js"

volumes:
  mysql_data:
